Capstone Project: E-Learning-Website
muhammedb8826/E-Learning-Project pull request #3
Opened 2023-02-10 15:27 UTC by muhammedb8826

In this project I have created two pages: 
- home page & 
- about page.

While making this project. 👍  I have created
- index.html to insert all the markup needed for the home page
- about.html to insert all the markup needed for the about page
- style.css to style the home page
- about.css to style about home page partially
- menu.js to make a mobile menu ( hamburger menu )
- db.js to store the information about the featured speaker's section.
- featured.js to create the markup or element dynamically to the page.

in order to check for the HTML/CSS/ javascript best practices I have installed
- stylelint
- eslint
- hint

2023-02-10 17:01 UTC, franclobo requested changes
Hi @muhammedb8826, 

# ♻️ Required changes ♻️ 

![so-close-jim-halpert](https://user-images.githubusercontent.com/58642949/218142601-8fc0512d-12d6-4cae-9ec4-76eee5a32b14.gif)

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Highlights

- No linter errors ✔️ 
- Correct Github flow ✔️ 
- Nice UI ✔️
- Good use of folder to organize the scripts and styles 💯 

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] Kindly record a 5 minutes video for professional documentation 👇🏽 

> Once you have finished the development of the project, you should record a video presenting the features of the project you built. It is a video with a maximum length of 5 minutes. The content of the video should include:
> A description of the project.
> A demo of the project features (different pages and different screen sizes).
> You should also highlight some interesting piece of code or something you built that you are very proud of.

- [ ] Please 🙏🏽 use the font family **Lato** in your text according to the original design, it is a project requirement to follow the design guidelines.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-02-10 17:01 UTC, franclobo commented on README.md
> +I would like to thank Microverse for teaching me how to code
- [ ] Please give the appropriate credit to the original author to avoid plagiarism 👇🏽 

> Original design idea by [Cindy Shin in Behance](https://www.behance.net/adagio07).
> 
> The [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/) requires that you give appropriate credit to the author. Therefore, you must do it in the README of your project.

2023-02-10 17:01 UTC, franclobo commented on README.md
> +- To be added soon
- [ ] Please 🙏🏽 deploy your app and add the Live Demo link to your README for professional documentation.

2023-02-10 17:01 UTC, franclobo commented on about.html
> +      <div class="logo">Coding with MB</div>
- [ ] Your logo should be a link 🔙 to back to the home 🏠  page it is a requirement for a better user experience. kindly add the `a` tag with the corresponding `href`
- [ ] The logo should be contained in the withe navbar, please 🙏🏽 correct it for best practices of HTML & CSS.

2023-02-10 17:01 UTC, franclobo commented on about.html
> +      </nav>
- [ ] Aditional to this white navbar there is a black navbar above it, please add the black navbar to be similar to the original design. Also, the content in the navbar has space on both sides, please add it. 👇🏽 

| Original design | Your design |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/218145002-ee5cffa5-723e-4510-afb9-5bd43419a470.png) | ![image](https://user-images.githubusercontent.com/58642949/218145153-3241277d-414b-4b3c-888c-aed6d5fa99fd.png) |

2023-02-10 17:01 UTC, franclobo commented on index.html
> +      </nav>
- [ ] Aditional to this white navbar there is a black navbar above it, please add the black navbar to be similar to the original design. Also, the content in the navbar has space on both sides, please add it. 👇🏽 

| Original design | Your design |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/218145002-ee5cffa5-723e-4510-afb9-5bd43419a470.png) | ![image](https://user-images.githubusercontent.com/58642949/218145153-3241277d-414b-4b3c-888c-aed6d5fa99fd.png) |

2023-02-10 17:01 UTC, franclobo commented on index.html
> +    </footer>
- [ ] Kindly correct the objects' alignment on the footer the logo is 🛅 left-aligned and the paragraph is ➡️ right-aligned.

2023-02-10 17:01 UTC, franclobo commented on about.html
> +      </footer>
- [ ] Kindly correct the objects' alignment on the footer the logo is 🛅 left-aligned and the paragraph is ➡️ right-aligned.

2023-02-10 17:01 UTC, franclobo commented on index.html
> +      <div class="logo">Coding with MB</div>
- [ ] The logo should be contained in the withe navbar, please 🙏🏽 correct it for best practices of HTML & CSS.

2023-02-10 17:01 UTC, franclobo commented on index.html
> +        <div class="hero-title">CREATIVE COMMONS GLOBAL SUMMIT 2023</div>
- [ ] The current topic of your project is **Codding with MB** so please 🙏🏽 change the title accordingly with the topic of your project to avoid confusion for a better user experience.

2023-02-10 17:01 UTC, franclobo commented on index.html
> +        </div>
- [ ] The project info should correspond to the topic, please 🙏🏽 change this info and describe what's your project about.

2023-02-10 17:01 UTC, franclobo commented on about.html
> +        <p class="year-description">CC Global Summit 2013 in Buenos Aires</p>
- [ ] In the original design we could see two different years, please 🙏🏽  correct the years in your design to be similar to the original design.

2023-02-11 13:14 UTC, binhussen approved these changes
Hi @muhammedb8826 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-11 13:55 UTC, merged

2023-06-01 08:58 UTC, muhammedb8826 commented on README.md
> +I would like to thank Microverse for teaching me how to code
okay, done!

2023-06-01 08:58 UTC, muhammedb8826 commented on README.md
> +- To be added soon
Alright, done

2023-06-01 08:59 UTC, muhammedb8826 commented on about.html
> +      <div class="logo">Coding with MB</div>
okay I'll do that

2023-06-01 08:59 UTC, muhammedb8826 commented on about.html
> +      </nav>
Got it, Thank you for reminding me

2023-06-01 09:00 UTC, muhammedb8826 commented on index.html
> +    </footer>
done

2023-06-01 09:00 UTC, muhammedb8826 commented on index.html
> +      <div class="logo">Coding with MB</div>
okay

2023-06-01 09:01 UTC, muhammedb8826 commented on index.html
> +        <div class="hero-title">CREATIVE COMMONS GLOBAL SUMMIT 2023</div>
okay

2023-06-01 09:02 UTC, muhammedb8826 commented
Thank you so much

2023-06-01 09:03 UTC, muhammedb8826 commented on about.html
> +        <p class="year-description">CC Global Summit 2013 in Buenos Aires</p>
okay, done

2023-06-01 09:03 UTC, muhammedb8826 commented on about.html
> +      </footer>
got it

2023-06-01 09:03 UTC, muhammedb8826 commented on index.html
> +      <div class="logo">Coding with MB</div>
okay

2023-06-01 09:04 UTC, muhammedb8826 commented on index.html
> +        </div>
okay